Package: {
  shape: package
  style: {
    stroke: blue
    fill: yellow
  }
}
Document: {
  shape: document
  style: {
    stroke: blue
    fill: white
    shadow: true
    underline: true
  }
}
Document -> Package: Files {
  style: {
    stroke: green
  }
}